// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBts27q9zGk8NCsYaTJI2tcemqoUHyHFcI',
    appId: '1:558686518462:web:4a830c164ebd56e47432ef',
    messagingSenderId: '558686518462',
    projectId: 'opinion-guard',
    authDomain: 'opinion-guard.firebaseapp.com',
    storageBucket: 'opinion-guard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzUiR8QPiOxPp5mUigUErlXH8dQFHivAY',
    appId: '1:558686518462:android:5174c2a8fa69ab4d7432ef',
    messagingSenderId: '558686518462',
    projectId: 'opinion-guard',
    storageBucket: 'opinion-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2beUzsR2n7S7tOO9xhYwbCVDz4RqTCPw',
    appId: '1:558686518462:ios:f827be71ddb2b16d7432ef',
    messagingSenderId: '558686518462',
    projectId: 'opinion-guard',
    storageBucket: 'opinion-guard.appspot.com',
    iosClientId: '558686518462-11gaipqlp4c1hfnmic8g18fqro5votcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.opinionguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2beUzsR2n7S7tOO9xhYwbCVDz4RqTCPw',
    appId: '1:558686518462:ios:f827be71ddb2b16d7432ef',
    messagingSenderId: '558686518462',
    projectId: 'opinion-guard',
    storageBucket: 'opinion-guard.appspot.com',
    iosClientId: '558686518462-11gaipqlp4c1hfnmic8g18fqro5votcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.opinionguard',
  );
}
